- packages/asgardex-client/lib/types.d.ts
- packages/asgardex-client/src/types.ts
Since we have to deal with UTXOs, input can be many txs.
> Fix type of `from` in `Tx`

- packages/xchain-binance/__tests__/client.test.ts
- packages/xchain-binance/lib/index.esm.js
- packages/xchain-binance/lib/index.js
- packages/xchain-binance/src/client.ts
In addition to #30 
Closes #28
> Revert `bncClient.getBalance`

- packages/xchain-cosmos/lib/client.d.ts
- packages/xchain-cosmos/lib/index.esm.js
- packages/xchain-cosmos/lib/index.js
- packages/xchain-cosmos/src/client.ts
- fix variable names.
- fix minor coding issues.
> fix-xchain-cosmos

- .github/workflows/on-push.yaml
- package.json
- packages/xchain-binance/package.json
- packages/xchain-bitcoin/__tests__/client.test.ts
- packages/xchain-bitcoin/package.json
- packages/xchain-bitcoin/src/blockchair-api.ts
- packages/xchain-bitcoin/src/client.ts
- packages/xchain-client/package.json
- packages/xchain-cosmos/package.json
- packages/xchain-crypto/package.json
- packages/xchain-crypto/src/crypto.ts
- packages/xchain-crypto/src/utils.ts
- packages/xchain-ethereum/package.json
- packages/xchain-thorchain/package.json
- packages/xchain-util/package.json
> Github Workflow for test + precommit linting + fix linting issues

- packages/xchain-binance/__tests__/client.test.ts
- packages/xchain-binance/src/client.ts
- packages/xchain-bitcoin/__tests__/client.test.ts
- packages/xchain-bitcoin/src/client.ts
- packages/xchain-client/src/types.ts
- packages/xchain-cosmos/__tests__/client.test.ts
- packages/xchain-cosmos/src/client.ts
- packages/xchain-ethereum/src/client.ts
- packages/xchain-thorchain/__tests__/client.test.ts
- packages/xchain-thorchain/src/client.ts
> Add `getExplorerUrl` #68

- packages/xchain-binance/src/client.ts
* fixed invalid asset parsing for getTransactions method
closes #80
> [xchain-binance] fix incorrect asset parsing at the getBalance method #80

- packages/xchain-binance/src/client.ts
* fixed binance asset parameter for getTransactinos method
closes #82
> [xchain-binance] incorrect asset parameter #82

- packages/xchain-binance/__tests__/client.test.ts
- packages/xchain-binance/__tests__/util.test.ts
- packages/xchain-binance/src/client.ts
- packages/xchain-binance/src/util.ts
- packages/xchain-client/src/types.ts
> Remove freeze/unfreeze

- packages/xchain-binance/CHANGELOG.md
- packages/xchain-binance/package.json
- packages/xchain-client/CHANGELOG.md
- packages/xchain-client/package.json
> Prepare `xchain-client@0.1.0` + `xchainjs/xchain-binance@4.0.0`

- packages/xchain-cosmos/CHANGELOG.md
- packages/xchain-cosmos/__tests__/sdk-client.test.ts
- packages/xchain-cosmos/package.json
- packages/xchain-cosmos/src/client.ts
- packages/xchain-cosmos/src/util.ts
- yarn.lock
> [xchain-cosmon] Fix import of `cosmos/codec`

- packages/xchain-thorchain/CHANGELOG.md
- packages/xchain-thorchain/package.json
- packages/xchain-thorchain/src/client.ts
+ prepare 0.4.2
+ use latest `xchain/cosmos@0.4.2`
> [xchain-thorchain] Fix import of `cosmos/codec`

- packages/xchain-crypto/CHANGELOG.md
- packages/xchain-crypto/package.json
- packages/xchain-crypto/src/index.ts
- `secp256k1`
- `ed25519`
- `utils`
Prepare `v.0.2.2`
> [xchain-crypto] Export content of other modules

- packages/xchain-binance/CHANGELOG.md
- packages/xchain-binance/__tests__/client.test.ts
- packages/xchain-binance/src/client.ts
- packages/xchain-bitcoin/CHANGELOG.md
- packages/xchain-bitcoin/__tests__/client.test.ts
- packages/xchain-bitcoin/src/client.ts
- packages/xchain-client/CHANGELOG.md
- packages/xchain-client/src/types.ts
- packages/xchain-cosmos/CHANGELOG.md
- packages/xchain-cosmos/__tests__/client.test.ts
- packages/xchain-cosmos/__tests__/sdk-client.test.ts
- packages/xchain-cosmos/src/client.ts
- packages/xchain-polkadot/CHANGELOG.md
- packages/xchain-polkadot/src/client.ts
- packages/xchain-thorchain/CHANGELOG.md
- packages/xchain-thorchain/src/client.ts
- add `getDefaultFees` (https://github.com/xchainjs/xchainjs-lib/issues/116)
- update mock tests for xchain-cosmos
> Add `getDefaultFees`

- packages/xchain-binance/CHANGELOG.md
- packages/xchain-binance/__tests__/client.test.ts
- packages/xchain-binance/src/client.ts
> Add `getSingleAndMultiFees`

- packages/xchain-util/CHANGELOG.md
- packages/xchain-util/README.md
- packages/xchain-util/src/chain.const.ts
- packages/xchain-util/src/chain.test.ts
- packages/xchain-util/src/chain.ts
> Update supported chains

- packages/xchain-bitcoin/src/types/blockchair-api-types.ts
- packages/xchain-ethereum/__mocks__/blockchair-api.ts
- packages/xchain-ethereum/__tests__/client.new.test.ts
- packages/xchain-ethereum/__tests__/client.test.ts
- packages/xchain-ethereum/jest.config.js
- packages/xchain-ethereum/jest.setup.js
- packages/xchain-ethereum/package.json
- packages/xchain-ethereum/src/blockchair-api.ts
- packages/xchain-ethereum/src/client.ts
- packages/xchain-ethereum/src/etherscan-api.ts
- packages/xchain-ethereum/src/types.ts
- packages/xchain-ethereum/src/types/blockchair-api-types.ts
- packages/xchain-ethereum/src/utils.ts
> Update `xchain-ethereum` to implement `XChainClient` interface #105

- packages/xchain-util/CHANGELOG.md
- packages/xchain-util/package.json
- yarn.lock
> Prepare + bump xchain-util@0.2.0

- packages/xchain-binance/CHANGELOG.md
- packages/xchain-binance/package.json
- packages/xchain-bitcoin/CHANGELOG.md
- packages/xchain-bitcoin/package.json
- packages/xchain-client/CHANGELOG.md
- packages/xchain-client/package.json
- packages/xchain-cosmos/CHANGELOG.md
- packages/xchain-cosmos/package.json
- packages/xchain-ethereum/CHANGELOG.md
- packages/xchain-ethereum/package.json
- packages/xchain-polkadot/CHANGELOG.md
- packages/xchain-polkadot/package.json
- packages/xchain-thorchain/CHANGELOG.md
- packages/xchain-thorchain/package.json
> Update / bump all clients for using latest xchain-util@0.2.0

- packages/xchain-cosmos/CHANGELOG.md
- packages/xchain-cosmos/src/cosmos/sdk-client.ts
- packages/xchain-cosmos/src/cosmos/types.ts
- packages/xchain-thorchain/CHANGELOG.md
- packages/xchain-thorchain/__tests__/client.test.ts
- packages/xchain-thorchain/__tests__/util.test.ts
- packages/xchain-thorchain/jest.config.js
- packages/xchain-thorchain/jest.setup.js
- packages/xchain-thorchain/src/client.ts
- packages/xchain-thorchain/src/index.ts
- packages/xchain-thorchain/src/messages.ts
- packages/xchain-thorchain/src/types.ts
- packages/xchain-thorchain/src/util.ts
- Update `transfer` (for `MsgSend`)
- Update `deposit` (for `MsgNativeTx`)
- Extract `signAndBroadcast` from `transfer` (xchain-cosmos)
> Update `transfer`, `deposit` for xchain-thorchain

- packages/xchain-cosmos/CHANGELOG.md
- packages/xchain-cosmos/package.json
- packages/xchain-thorchain/CHANGELOG.md
- packages/xchain-thorchain/package.json
- xchain-cosmos@0.5.1
- xchain-thorchain@0.6.0
> Prepare + bump xchain-thorchain@0.6.0

- packages/xchain-thorchain/CHANGELOG.md
- packages/xchain-thorchain/__tests__/client.test.ts
- packages/xchain-thorchain/package.json
- packages/xchain-thorchain/src/client.ts
- packages/xchain-thorchain/src/types.ts
- Add `setClientUrl`
- Add `getDefaultClientUrl`
- Fix client URL for multichain testnet (`https://testnet.thornode.thorchain.info`)
> Update xchain-thorchain (prepare bump @0.6.1)

- packages/xchain-binance/CHANGELOG.md
- packages/xchain-binance/src/client.ts
- packages/xchain-bitcoin/CHANGELOG.md
- packages/xchain-bitcoin/src/client.ts
- packages/xchain-client/CHANGELOG.md
- packages/xchain-client/src/types.ts
- packages/xchain-cosmos/CHANGELOG.md
- packages/xchain-cosmos/src/client.ts
- packages/xchain-polkadot/CHANGELOG.md
- packages/xchain-polkadot/__tests__/client.test.ts
- packages/xchain-polkadot/package.json
- packages/xchain-polkadot/src/client.ts
- packages/xchain-thorchain/CHANGELOG.md
- packages/xchain-thorchain/src/client.ts
> Extract `validateAddress` into `XChainClient` interface

- packages/xchain-binance/CHANGELOG.md
- packages/xchain-binance/__tests__/util.test.ts
- packages/xchain-binance/src/client.ts
- packages/xchain-binance/src/util.ts
- packages/xchain-bitcoin/CHANGELOG.md
- packages/xchain-bitcoin/__tests__/client.test.ts
- packages/xchain-bitcoin/src/blockchair-api.ts
- packages/xchain-bitcoin/src/client.ts
- packages/xchain-bitcoin/src/const.ts
- packages/xchain-bitcoin/src/ledger.ts
- packages/xchain-bitcoin/src/types/ledger.ts
- packages/xchain-bitcoin/src/utils.ts
- packages/xchain-ethereum/CHANGELOG.md
- packages/xchain-ethereum/src/blockchair-api.ts
- packages/xchain-ethereum/src/client.ts
- packages/xchain-ethereum/src/etherscan-api.ts
- packages/xchain-ethereum/src/types/client-types.ts
- packages/xchain-ethereum/src/types/index.ts
- packages/xchain-ethereum/src/utils.ts
- packages/xchain-polkadot/src/client.ts
- packages/xchain-polkadot/src/util.ts
- packages/xchain-thorchain/package.json
- packages/xchain-thorchain/src/util.ts
Update comments for xchain-ethereum, xchain-bitcoin, xchain-binance.
> Update `xchain-ethereum`, `xchain-bitcoin`, `xchain-binance`

- packages/xchain-binance/src/client.ts
- packages/xchain-thorchain/src/client.ts
* This issue causes something wrong when generating the documentation.
> Fix some issues on the comments.

- packages/xchain-thorchain/__tests__/client.test.ts
- packages/xchain-thorchain/src/client.ts
- packages/xchain-thorchain/src/types/client-types.ts
> xchain-thorcahin/getExplorerUrl update based on network

- packages/xchain-util/CHANGELOG.md
- packages/xchain-util/package.json
- packages/xchain-util/src/asset.test.ts
- packages/xchain-util/src/asset.ts
> [xchain-util] Fix decimal handling in `assetToBase`

- packages/xchain-ethereum/CHANGELOG.md
- packages/xchain-ethereum/__tests__/client.test.ts
- packages/xchain-ethereum/src/client.ts
- packages/xchain-ethereum/src/ethplorer-api.ts
- packages/xchain-ethereum/src/types/client-types.ts
- packages/xchain-ethereum/src/utils.ts
> Default values for `ethplorerUrl` and `explorerUrl`

- packages/xchain-thorchain/CHANGELOG.md
- packages/xchain-thorchain/src/client.ts
- packages/xchain-thorchain/src/types/messages.ts
> Move fromJson outside of MsgNativeTx

- packages/xchain-binance/CHANGELOG.md
- packages/xchain-binance/package.json
- packages/xchain-binance/src/index.ts
- packages/xchain-bitcoin/CHANGELOG.md
- packages/xchain-bitcoin/package.json
- packages/xchain-bitcoin/src/index.ts
- packages/xchain-ethereum/CHANGELOG.md
- packages/xchain-ethereum/package.json
- packages/xchain-ethereum/src/index.ts
> Fix prepare-bump

- packages/xchain-thorchain/CHANGELOG.md
- packages/xchain-thorchain/__tests__/client.test.ts
- packages/xchain-thorchain/package.json
- packages/xchain-thorchain/src/client.ts
- packages/xchain-thorchain/src/types/messages.ts
- use /thorchain/deposit API to build deposit transaction.
> Fix xchain-thorchain/deposit

- packages/xchain-bitcoincash/__mocks__/api.ts
- packages/xchain-bitcoincash/__tests__/client.test.ts
- packages/xchain-bitcoincash/src/client.ts
- packages/xchain-bitcoincash/src/index.ts
- packages/xchain-bitcoincash/src/types/api-types.ts
- packages/xchain-bitcoincash/src/utils.ts
- change API url to api.bitcore.io (rest.bitcoin.com doesn't support bch testnet anymore.)
- add `getTransactionData`
> Impl `getTransactionData`

- packages/xchain-thorchain/CHANGELOG.md
- packages/xchain-thorchain/__tests__/client.test.ts
- packages/xchain-thorchain/package.json
- packages/xchain-thorchain/src/client.ts
> [xchain-thorchain] added getExplorerNodeUrl

- packages/xchain-cosmos/CHANGELOG.md
- packages/xchain-cosmos/__tests__/client.test.ts
- packages/xchain-cosmos/__tests__/sdk-client.test.ts
- packages/xchain-cosmos/__tests__/util.test.ts
- packages/xchain-cosmos/package.json
- packages/xchain-cosmos/src/cosmos/sdk-client.ts
- packages/xchain-cosmos/src/cosmos/types.ts
- packages/xchain-thorchain/CHANGELOG.md
- packages/xchain-thorchain/__tests__/client.test.ts
- packages/xchain-thorchain/__tests__/util.test.ts
- packages/xchain-thorchain/package.json
- packages/xchain-thorchain/src/client.ts
- packages/xchain-thorchain/src/types/messages.ts
- packages/xchain-thorchain/src/util.ts
- include incoming transactions
- fix `deposit` transaction
- prepare bump (xchain-cosmos@0.8.1, xchain-thorchain@0.10.1)
> Fix `getTransactions`

- packages/xchain-bitcoincash/CHANGELOG.md
- packages/xchain-bitcoincash/__tests__/client.test.ts
- packages/xchain-bitcoincash/src/utils.ts
- packages/xchain-ethereum/CHANGELOG.md
- packages/xchain-ethereum/src/index.ts
- packages/xchain-litecoin/CHANGELOG.md
- packages/xchain-litecoin/src/client.ts
- packages/xchain-litecoin/src/index.ts
- packages/xchain-litecoin/src/sochain-api.ts
- packages/xchain-litecoin/src/utils.ts
- packages/xchain-util/src/asset.ts
Fix #209 #210 
Fix derivation path for `LTC` and `BCH`
> `ETH_DECIMAL`, `LTC_DECIMAL `

- packages/xchain-ethereum/__tests__/client.test.ts
- packages/xchain-ethereum/src/client.ts
- packages/xchain-ethereum/src/types/client-types.ts
> eth package allows optional infura provider

- packages/xchain-binance/CHANGELOG.md
- packages/xchain-binance/README.md
- packages/xchain-bitcoin/CHANGELOG.md
- packages/xchain-bitcoin/README.md
- packages/xchain-bitcoincash/CHANGELOG.md
- packages/xchain-bitcoincash/README.md
- packages/xchain-cosmos/CHANGELOG.md
- packages/xchain-cosmos/README.md
- packages/xchain-ethereum/CHANGELOG.md
- packages/xchain-ethereum/README.md
- packages/xchain-litecoin/CHANGELOG.md
- packages/xchain-litecoin/README.md
- packages/xchain-polkadot/CHANGELOG.md
- packages/xchain-polkadot/README.md
- packages/xchain-thorchain/CHANGELOG.md
- packages/xchain-thorchain/README.md
> ADD: Service Provider Details

- packages/xchain-bitcoincash/CHANGELOG.md
- packages/xchain-bitcoincash/README.md
- packages/xchain-bitcoincash/__mocks__/api.ts
- packages/xchain-bitcoincash/__tests__/client.test.ts
- packages/xchain-bitcoincash/__tests__/utils.test.ts
- packages/xchain-bitcoincash/package.json
- packages/xchain-bitcoincash/src/client.ts
- packages/xchain-bitcoincash/src/haskoin-api.ts
- packages/xchain-bitcoincash/src/types/api-types.ts
- packages/xchain-bitcoincash/src/utils.ts
- add `scanUTXOs`, `transfer`, `fee`
> Update Bitcoin Cash

- packages/xchain-ethereum/CHANGELOG.md
- packages/xchain-ethereum/package.json
> [xchain-ethereum] bump version to v0.10.3

- packages/xchain-binance/CHANGELOG.md
- packages/xchain-binance/README.md
- packages/xchain-binance/package.json
- packages/xchain-bitcoin/CHANGELOG.md
- packages/xchain-bitcoin/README.md
- packages/xchain-bitcoin/package.json
- packages/xchain-bitcoincash/CHANGELOG.md
- packages/xchain-bitcoincash/README.md
- packages/xchain-bitcoincash/package.json
- packages/xchain-client/CHANGELOG.md
- packages/xchain-client/package.json
- packages/xchain-cosmos/CHANGELOG.md
- packages/xchain-cosmos/README.md
- packages/xchain-cosmos/package.json
- packages/xchain-ethereum/CHANGELOG.md
- packages/xchain-ethereum/README.md
- packages/xchain-ethereum/package.json
- packages/xchain-litecoin/CHANGELOG.md
- packages/xchain-litecoin/README.md
- packages/xchain-litecoin/package.json
- packages/xchain-polkadot/CHANGELOG.md
- packages/xchain-polkadot/README.md
- packages/xchain-polkadot/package.json
- packages/xchain-thorchain/CHANGELOG.md
- packages/xchain-thorchain/README.md
- packages/xchain-thorchain/package.json
- packages/xchain-util/package.json
- yarn.lock
> Fix `peerDependencies`

- packages/xchain-ethereum/CHANGELOG.md
- packages/xchain-ethereum/package.json
- packages/xchain-ethereum/src/client.ts
- packages/xchain-ethereum/src/types/client-types.ts
> fix estimateGasLimit to consider memo in xchain-eth

- packages/xchain-litecoin/CHANGELOG.md
- packages/xchain-litecoin/README.md
- packages/xchain-litecoin/__mocks__/sochain.ts
- packages/xchain-litecoin/__tests__/client.test.ts
- packages/xchain-litecoin/jest.config.js
- packages/xchain-litecoin/jest.setup.js
- packages/xchain-litecoin/src/bitaps-api.ts
- packages/xchain-litecoin/src/client.ts
- packages/xchain-litecoin/src/sochain-api.ts
- packages/xchain-litecoin/src/types/bitaps-api-types.ts
- packages/xchain-litecoin/src/types/client-types.ts
- packages/xchain-litecoin/src/types/common.ts
- packages/xchain-litecoin/src/types/ledger.ts
- packages/xchain-litecoin/src/types/sochain-api-types.ts
- packages/xchain-litecoin/src/utils.ts
> Update litecoin transaction broadcast.

- packages/xchain-ethereum/CHANGELOG.md
- packages/xchain-ethereum/src/client.ts
> Fix getDefaultExplorerURL of xchain-ethereum

- packages/xchain-thorchain/CHANGELOG.md
- packages/xchain-thorchain/package.json
- packages/xchain-thorchain/src/client.ts
- packages/xchain-thorchain/src/util.ts
- fix `getTransactions` - sort from latest.
- fix Decimals
- prepare bump @0.11.1
> Fix `getTransactions`, `DECIMAL`

- packages/xchain-binance/CHANGELOG.md
- packages/xchain-binance/__tests__/client.test.ts
- packages/xchain-binance/package.json
- packages/xchain-binance/src/client.ts
- packages/xchain-bitcoin/CHANGELOG.md
- packages/xchain-bitcoin/package.json
- packages/xchain-bitcoincash/CHANGELOG.md
- packages/xchain-bitcoincash/package.json
- packages/xchain-client/CHANGELOG.md
- packages/xchain-client/package.json
- packages/xchain-client/src/types.ts
- packages/xchain-cosmos/CHANGELOG.md
- packages/xchain-cosmos/package.json
- packages/xchain-cosmos/src/client.ts
- packages/xchain-ethereum/CHANGELOG.md
- packages/xchain-ethereum/__tests__/client.test.ts
- packages/xchain-ethereum/package.json
- packages/xchain-ethereum/src/client.ts
- packages/xchain-litecoin/CHANGELOG.md
- packages/xchain-litecoin/package.json
- packages/xchain-polkadot/CHANGELOG.md
- packages/xchain-polkadot/package.json
- packages/xchain-polkadot/src/client.ts
- packages/xchain-thorchain/CHANGELOG.md
- packages/xchain-thorchain/package.json
- packages/xchain-thorchain/src/client.ts
- yarn.lock
> Update getBalance to accept a list of assets (not just one)

- packages/xchain-bitcoincash/CHANGELOG.md
- packages/xchain-bitcoincash/README.md
- packages/xchain-bitcoincash/__mocks__/api.ts
- packages/xchain-bitcoincash/__tests__/client.test.ts
- packages/xchain-bitcoincash/__tests__/utils.test.ts
- packages/xchain-bitcoincash/jest.config.js
- packages/xchain-bitcoincash/jest.setup.js
- packages/xchain-bitcoincash/package.json
- packages/xchain-bitcoincash/rollup.config.js
- packages/xchain-bitcoincash/src/client.ts
- packages/xchain-bitcoincash/src/haskoin-api.ts
- packages/xchain-bitcoincash/src/node-api.ts
- packages/xchain-bitcoincash/src/types/api-types.ts
- packages/xchain-bitcoincash/src/types/bitcoincashjs-types.ts
- packages/xchain-bitcoincash/src/types/client-types.ts
- packages/xchain-bitcoincash/src/types/coininfo.d.ts
- packages/xchain-bitcoincash/src/types/index.ts
- packages/xchain-bitcoincash/src/types/node-api-types.ts
- packages/xchain-bitcoincash/src/utils.ts
- yarn.lock
> Change `xchain-bitcoincash` with new lib `@psf/bitcoincashjs-lib`

- packages/xchain-util/CHANGELOG.md
- packages/xchain-util/package.json
- packages/xchain-util/src/chain.test.ts
- packages/xchain-util/src/chain.ts
- update chainToString to support bitcoin cash
- update tests for chain.ts
- prepare @0.2.4
> Update chainToString to support bitcoin cash

- packages/xchain-binance/CHANGELOG.md
- packages/xchain-binance/src/client.ts
- packages/xchain-bitcoin/CHANGELOG.md
- packages/xchain-bitcoin/src/utils.ts
- packages/xchain-bitcoincash/CHANGELOG.md
- packages/xchain-bitcoincash/src/utils.ts
- packages/xchain-cosmos/CHANGELOG.md
- packages/xchain-cosmos/src/util.ts
- packages/xchain-ethereum/CHANGELOG.md
- packages/xchain-ethereum/src/client.ts
- packages/xchain-litecoin/CHANGELOG.md
- packages/xchain-litecoin/src/utils.ts
- packages/xchain-thorchain/CHANGELOG.md
- packages/xchain-thorchain/src/util.ts
> Replace `find`, `findIndex`

- packages/xchain-binance/CHANGELOG.md
- packages/xchain-binance/package.json
- packages/xchain-bitcoin/CHANGELOG.md
- packages/xchain-bitcoin/package.json
- packages/xchain-bitcoincash/CHANGELOG.md
- packages/xchain-bitcoincash/package.json
- packages/xchain-client/CHANGELOG.md
- packages/xchain-client/package.json
- packages/xchain-client/src/types.ts
- packages/xchain-cosmos/CHANGELOG.md
- packages/xchain-cosmos/package.json
- packages/xchain-ethereum/CHANGELOG.md
- packages/xchain-ethereum/package.json
- packages/xchain-ethereum/src/client.ts
- packages/xchain-litecoin/CHANGELOG.md
- packages/xchain-litecoin/package.json
- packages/xchain-polkadot/CHANGELOG.md
- packages/xchain-polkadot/package.json
- packages/xchain-thorchain/CHANGELOG.md
- packages/xchain-thorchain/package.json
> update getTransactionData type

- packages/xchain-util/CHANGELOG.md
- packages/xchain-util/package.json
- packages/xchain-util/src/asset.test.ts
- packages/xchain-util/src/asset.ts
> Update `formatAssetAmountCurrency` to remove bracket

- packages/xchain-bitcoincash/CHANGELOG.md
- packages/xchain-bitcoincash/__tests__/client.test.ts
- packages/xchain-bitcoincash/package.json
- packages/xchain-bitcoincash/src/client.ts
- packages/xchain-bitcoincash/src/utils.ts
prepare xchain-bitcoincash@0.7.1
> xchain-bitcoincash: Include unconfirmed balances

- packages/xchain-ethereum/CHANGELOG.md
- packages/xchain-ethereum/package.json
- packages/xchain-ethereum/src/client.ts
Fix #271 
- fix conversion of BaseAmount.
- prepare xchain-ethereum@0.14.1
> Fix BaseAmount conversion

- packages/xchain-ethereum/CHANGELOG.md
- packages/xchain-ethereum/__mocks__/etherscan-api.ts
- packages/xchain-ethereum/__mocks__/index.ts
- packages/xchain-ethereum/__tests__/util.test.ts
- packages/xchain-ethereum/package.json
- packages/xchain-ethereum/src/client.ts
- packages/xchain-ethereum/src/index.ts
- packages/xchain-ethereum/src/utils.ts
- export Client.`estimateGasPrices`, Util.`getFee`
- fix Util.`getTokenAddress`
- save `etherscanApiKey` in Client
This pr is for fee handling using `estimateCall` on ASGDX.
and this will close #274
> Fix xchain-ethereum

- packages/xchain-thorchain/CHANGELOG.md
- packages/xchain-thorchain/__tests__/client.test.ts
- packages/xchain-thorchain/package.json
- packages/xchain-thorchain/src/client.ts
- Changed `getDefaultExplorerUrl` to return valid urls
- prepared `v0.13.1`
> [xchain-thorchain] fix explorer urls

- packages/xchain-ethereum/CHANGELOG.md
- packages/xchain-ethereum/__tests__/client.test.ts
- packages/xchain-ethereum/package.json
- packages/xchain-ethereum/src/client.ts
close #284 
prepare xchain-ethereum@0.15.0
> Provide getDecimal(assetAddress)

- packages/xchain-ethereum/CHANGELOG.md
- packages/xchain-ethereum/__mocks__/ethplorer-api.ts
- packages/xchain-ethereum/__tests__/client.mainnet.test.ts
- packages/xchain-ethereum/__tests__/client.testnet.test.ts
- packages/xchain-ethereum/package.json
- packages/xchain-ethereum/src/client.ts
- packages/xchain-ethereum/src/ethplorer-api.ts
- packages/xchain-ethereum/src/types/ethplorer-api-types.ts
- packages/xchain-ethereum/src/types/index.ts
- packages/xchain-ethereum/src/utils.ts
- yarn.lock
> Integrate Ethplorer for mainnet

- packages/xchain-ethereum/CHANGELOG.md
- packages/xchain-ethereum/__tests__/util.test.ts
- packages/xchain-ethereum/package.json
- packages/xchain-ethereum/src/client.ts
- packages/xchain-ethereum/src/etherscan-api.ts
- packages/xchain-ethereum/src/types/ethplorer-api-types.ts
- packages/xchain-ethereum/src/utils.ts
> Update tests and error messages

- packages/xchain-bitcoincash/CHANGELOG.md
- packages/xchain-bitcoincash/__tests__/client.test.ts
- packages/xchain-bitcoincash/package.json
- packages/xchain-bitcoincash/src/client.ts
- packages/xchain-bitcoincash/src/utils.ts
remove `bchtest:` & `bitcoincash:`
> Remove address prefix from bitcoincash

- packages/xchain-thorchain/CHANGELOG.md
- packages/xchain-thorchain/__tests__/client.test.ts
- packages/xchain-thorchain/package.json
- packages/xchain-thorchain/src/client.ts
> Fix thorchain explorer url

- packages/xchain-util/CHANGELOG.md
- packages/xchain-util/package.json
- packages/xchain-util/src/asset.ts
> Remove decimal + rounddown by div operation

- packages/xchain-thorchain/CHANGELOG.md
- packages/xchain-thorchain/package.json
- packages/xchain-thorchain/src/client.ts
updates fee.gas to 1000000 (one million) in deposit
> [xchain-thorchain] Change fee.gas to `1000000` in deposit

- packages/xchain-thorchain/CHANGELOG.md
- packages/xchain-thorchain/package.json
- packages/xchain-thorchain/src/client.ts
- packages/xchain-thorchain/src/types/client-types.ts
+ Remove re-try for sending deposit txs
> [thorchain] updates fee.gas to 10 mil in deposit due to failing withdraws

- packages/xchain-thorchain/CHANGELOG.md
- packages/xchain-thorchain/__tests__/client.test.ts
- packages/xchain-thorchain/package.json
- packages/xchain-thorchain/src/client.ts
- packages/xchain-thorchain/src/util.ts
- added `filterFn` as an optional filter function for `getTransactions` https://github.com/xchainjs/xchainjs-lib/pull/306/commits/b61a74dfdbecf6d53e5e4f3bcd0e6b19bcc2c0cd#diff-859d04d1597312189391129aa4e4d0f913a7c3839ceed54cacd18e8bd2424f20R375
> chore: export utils & thorchain.`getCosmosClient`

- packages/xchain-ethereum/CHANGELOG.md
- packages/xchain-ethereum/package.json
- packages/xchain-ethereum/src/client.ts
https://github.com/EverexIO/Ethplorer/issues/209
- get ETH Balance directly using provider
- update `getBalance` method
> Fix wrong eth balance issue due to internal txn

- packages/xchain-binance/__tests__/client.test.ts
- packages/xchain-binance/src/client.ts
support derivation path(sub account index) to binance client
> feat: support derivation path(binance)

- packages/xchain-thorchain/__tests__/client.test.ts
- packages/xchain-thorchain/src/client.ts
- packages/xchain-thorchain/src/types/client-types.ts
support derivation path(sub account index) to thor client
> feat: support derivation path(thor)

- packages/xchain-ethereum/CHANGELOG.md
- packages/xchain-ethereum/__tests__/client.mainnet.test.ts
- packages/xchain-ethereum/__tests__/client.testnet.test.ts
- packages/xchain-ethereum/package.json
- packages/xchain-ethereum/src/client.ts
- Get ETH balance directly from the provider
- Remove unit test for `getBalance` method
- Bump up version to `0.21.0`
> Fix eth balance issue

- packages/xchain-bitcoin/CHANGELOG.md
- packages/xchain-bitcoin/package.json
- packages/xchain-bitcoin/src/utils.ts
- packages/xchain-bitcoincash/CHANGELOG.md
- packages/xchain-bitcoincash/package.json
- packages/xchain-bitcoincash/src/utils.ts
- packages/xchain-litecoin/CHANGELOG.md
- packages/xchain-litecoin/package.json
- packages/xchain-litecoin/src/utils.ts
> Fix dust error occurred by accumulating memo output

- packages/xchain-client/CHANGELOG.md
- packages/xchain-client/package.json
- packages/xchain-client/src/types.ts
> Make `walletIndex` optional in `getAddress`

- packages/xchain-thorchain/CHANGELOG.md
- packages/xchain-thorchain/__tests__/client.test.ts
- packages/xchain-thorchain/__tests__/util.test.ts
- packages/xchain-thorchain/package.json
- packages/xchain-thorchain/src/client.ts
- packages/xchain-thorchain/src/types/client-types.ts
- packages/xchain-thorchain/src/util.ts
> [xchain-thorchain] Use `viewblock` as default explorer

- packages/xchain-bitcoin/CHANGELOG.md
- packages/xchain-bitcoin/__tests__/utils.test.ts
- packages/xchain-bitcoin/package.json
- packages/xchain-bitcoin/src/haskoin-api.ts
- packages/xchain-bitcoin/src/utils.ts
> hotfix: replace getbalance, getunspenttxs api from sochain to haskoin

- packages/xchain-bitcoin/CHANGELOG.md
- packages/xchain-bitcoin/__mocks__/haskoin.ts
- packages/xchain-bitcoin/__mocks__/response/balances/haskoin-bc1address.json
- packages/xchain-bitcoin/__tests__/haskoin-api.test.ts
- packages/xchain-bitcoin/package.json
- packages/xchain-bitcoin/src/haskoin-api.ts
- packages/xchain-bitcoin/src/sochain-api.ts
> [xchain-btc] Quick fix `getBalance` (haskoin API)

- packages/xchain-bitcoincash/CHANGELOG.md
- packages/xchain-bitcoincash/__tests__/client.test.ts
- packages/xchain-bitcoincash/__tests__/utils.test.ts
- packages/xchain-bitcoincash/package.json
- packages/xchain-bitcoincash/src/client.ts
- packages/xchain-bitcoincash/src/utils.ts
> Resolve: "ADD: BCH legacy address validation"

- packages/xchain-ethereum/CHANGELOG.md
- packages/xchain-ethereum/__mocks__/responses/inbound_addresses_mainnet.json
- packages/xchain-ethereum/__mocks__/responses/inbound_addresses_testnet.json
- packages/xchain-ethereum/__mocks__/thornode-api.ts
- packages/xchain-ethereum/__tests__/client.mainnet.test.ts
- packages/xchain-ethereum/__tests__/client.testnet.test.ts
- packages/xchain-ethereum/package.json
- packages/xchain-ethereum/src/client.ts
> [xchain-eth] Fix `estimateGasPrices`

- packages/xchain-bitcoincash/src/client.ts
subtle bug for sender address derivation
> added index for sender

- packages/xchain-ethereum/CHANGELOG.md
- packages/xchain-ethereum/package.json
- packages/xchain-ethereum/src/client.ts
> [xchain-eth] Provide overridden `getFees` in `EthereumClient` interface

- packages/xchain-thorchain/CHANGELOG.md
- packages/xchain-thorchain/package.json
- packages/xchain-thorchain/src/client.ts
Based on discussion at Discord https://discord.com/channels/838986635756044328/842252968253456424/864781708649955338
And bump to `v0.17.04`.
> [xchain-thorchain] Bump gas to `25m`

- packages/xchain-util/CHANGELOG.md
- packages/xchain-util/package.json
- packages/xchain-util/src/asset.test.ts
- packages/xchain-util/src/asset.ts
> [xchain-util] Fix currency symbol for XRUNE

- packages/xchain-binance/CHANGELOG.md
- packages/xchain-binance/package.json
- packages/xchain-binance/rollup.config.js
- packages/xchain-client/CHANGELOG.md
- packages/xchain-client/package.json
- packages/xchain-client/src/BaseXChainClient.ts
- packages/xchain-cosmos/CHANGELOG.md
- packages/xchain-cosmos/package.json
- packages/xchain-thorchain/CHANGELOG.md
- packages/xchain-thorchain/package.json
- packages/xchain-thorchain/rollup.config.js
- Updatedrollupjs to include axios to enlable usage on node
- optimized BaseXchainClient to skip creating an addres that just gets thown away in the constructor
- upgraded to     "cosmos-client": "0.42.7"
> fixes for 398, 401, 402

- packages/xchain-binance/CHANGELOG.md
- packages/xchain-binance/package.json
- packages/xchain-binance/src/client.ts
- packages/xchain-cosmos/CHANGELOG.md
- packages/xchain-cosmos/package.json
- packages/xchain-thorchain/CHANGELOG.md
- packages/xchain-thorchain/package.json
- yarn.lock
- also including the fix submitted in  https://github.com/xchainjs/xchainjs-lib/pull/407
> FIX -rollback  thorchain & cosmos to  "cosmos-client": "0.39.2"

- .github/workflows/on-push.yaml
> [GH action] Update to run with Node 14.x

- packages/xchain-crypto/CHANGELOG.md
- packages/xchain-crypto/package.json
- packages/xchain-crypto/src/utils.ts
- yarn.lock
> [xchain-crypto] Update to latest dependencies (01-09-2021)

- packages/xchain-client/CHANGELOG.md
- packages/xchain-client/package.json
> [xchain-client] Update to latest dependencies (01-09-2021)

- packages/xchain-binance/CHANGELOG.md
- packages/xchain-binance/package.json
> [xchain-binance] Update to latest dependencies (01-09-2021)

- packages/xchain-bitcoincash/CHANGELOG.md
- packages/xchain-bitcoincash/package.json
- yarn.lock
> Resolve: [xchain-bitcoincash] Update to latest dependencies

- packages/xchain-ethereum/CHANGELOG.md
- packages/xchain-ethereum/__tests__/client.testnet.test.ts
- packages/xchain-ethereum/package.json
- yarn.lock
> Resolve: [xchain-ethereum] Update to latest dependencies

- packages/xchain-thorchain/CHANGELOG.md
- packages/xchain-thorchain/package.json
- packages/xchain-thorchain/src/client.ts
- packages/xchain-thorchain/src/util.ts
Needed for Ledger support in AGARDEX - PR https://github.com/thorchain/asgardex-electron/pull/1744
Close #437
> Extract helpers + prepare/bump next version

- packages/xchain-thorchain/CHANGELOG.md
- packages/xchain-thorchain/package.json
- packages/xchain-thorchain/src/util.ts
> [xchain-thorchain] Increase gas limit to 500m

- packages/xchain-cosmos/CHANGELOG.md
- packages/xchain-cosmos/package.json
- packages/xchain-cosmos/src/cosmos/sdk-client.ts
- packages/xchain-thorchain/CHANGELOG.md
- packages/xchain-thorchain/package.json
> [xchain-cosmos] Use `sync` mode for broadcasting txs

- packages/xchain-thorchain/CHANGELOG.md
- packages/xchain-thorchain/README.md
- packages/xchain-thorchain/__tests__/client.test.ts
- packages/xchain-thorchain/package.json
- packages/xchain-thorchain/src/client.ts
> [xchain-thorchain]: `getPriv|PubKey` + add tests + bump version

- packages/xchain-cosmos/CHANGELOG.md
- packages/xchain-cosmos/package.json
- packages/xchain-cosmos/src/cosmos/sdk-client.ts
from `signAndBroadcast` in `CosmosSDKClient`
Prepare xchain-cosmos@0.13.9
> [xchain-cosmos] Extract `sign` and `broadcast`

- packages/xchain-bitcoin/CHANGELOG.md
- packages/xchain-bitcoin/__tests__/haskoin-api.test.ts
- packages/xchain-bitcoin/__tests__/utils.test.ts
- packages/xchain-bitcoin/package.json
- packages/xchain-bitcoin/src/client.ts
- packages/xchain-bitcoin/src/haskoin-api.ts
- packages/xchain-bitcoin/src/types/client-types.ts
- packages/xchain-bitcoin/src/types/ledger.ts
- packages/xchain-bitcoin/src/types/sochain-api-types.ts
- packages/xchain-bitcoin/src/utils.ts
- Add `haskoinUrl` parameter in `constructor` + pass it down to misc. helpers
- Update tests
- Bump v0.17.0
Close #458
> Resolve: Make haskoin url configurable

- packages/xchain-ethereum/CHANGELOG.md
- packages/xchain-ethereum/package.json
- packages/xchain-ethereum/src/client.ts
> [xchain-eth] Fix getDefaultProvider for stagenet

- packages/xchain-util/CHANGELOG.md
- packages/xchain-util/package.json
- packages/xchain-util/src/asset.ts
- packages/xchain-util/src/chain.test.ts
- packages/xchain-util/src/chain.ts
> [xchain-util] Add DOGE

- packages/xchain-thorchain/CHANGELOG.md
- packages/xchain-thorchain/package.json
- packages/xchain-thorchain/src/client.ts
- packages/xchain-thorchain/src/types/messages.ts
- packages/xchain-thorchain/src/util.ts
- use cosmos node info to get network so that chain ID can be set
> getChainId from thornode before posting to deposit handler

- packages/xchain-doge/CHANGELOG.md
- packages/xchain-doge/package.json
- packages/xchain-doge/src/client.ts
- packages/xchain-doge/src/index.ts
- packages/xchain-doge/src/utils.ts
> Clean-up xchain-doge + bump 0.1.1

- packages/xchain-litecoin/CHANGELOG.md
- packages/xchain-litecoin/package.json
- yarn.lock
> Prepare xchain-ltc@071

- packages/xchain-thorchain/CHANGELOG.md
- packages/xchain-thorchain/package.json
- packages/xchain-thorchain/src/util.ts
> Resolve: [xchain-thorchain] Update chain-id for testnet

- packages/xchain-terra/CHANGELOG.md
- packages/xchain-terra/src/client.ts
> Resolve: [xchain-terra] Improve transfer

- packages/xchain-bitcoin/CHANGELOG.md
- packages/xchain-bitcoin/package.json
- packages/xchain-bitcoin/src/haskoin-api.ts
> [xchain-btc] Handle Haskoins 500 issue

- packages/xchain-bitcoin/CHANGELOG.md
- packages/xchain-bitcoin/package.json
- packages/xchain-bitcoin/src/utils.ts
incl. bump xchain-btc@0.18.1
Fix #503
> [xchain-btc] Fix fee estimation

- packages/xchain-binance/README.md
Updated only the 'readme'  of the [xchain-bnb] package to better reflect package's functions and added working code snippets for easier integration.
> 515 xchain bnbreadmeupdate

- packages/xchain-terra/README.md
Readme file now up to date with the package's functions and added working code snippets
> Updated xchain-Terra Readme 

- packages/xchain-bitcoincash/README.md
Only Touched Readme file. Updated contents to reflect latest functions. Added working code snippets for clarity
> 520 xchain bitcoincash update readme

- packages/xchain-litecoin/README.md
Only touched readme. Updated to reflect latest package's functions.
Added working examples
> 523 xchain litecoin update readme

- packages/xchain-doge/README.md
Only touched Readme. 
Updated to reflect packages underlying functions
Added working code examples
> Updated xchain-doge Readme

- packages/xchain-terra/CHANGELOG.md
- packages/xchain-terra/package.json
- packages/xchain-terra/src/client.ts
https://github.com/xchainjs/xchainjs-lib/blob/0f472d6a34e3584ccb2532c891e04eea31fe08dd/packages/xchain-terra/src/client.ts#L123-L125
> Fix `getExplorerTxUrl` returning `explorerAddressURL`

- packages/xchain-thorchain/README.md
Only touched Readme. 
Update to better reflect underlying functions.
> 530 xchain thorchain update readme

- packages/xchain-ethereum/README.md
Only touched Readme. 
Updated to reflect packages underlying functions
Added working code examples
> [xchain-ethereum] Updated read me to reflect packages underlying functions 

- packages/xchain-crypto/README.md
- packages/xchain-terra/README.md
Updated readme to be consistent with other packages. 
Added working examples
Adjusted a broken table in xchain-terra readme. :)
> Updated Readme with working code snippets

- packages/xchain-doge/CHANGELOG.md
- packages/xchain-doge/src/blockcypher-api.ts
- packages/xchain-terra/CHANGELOG.md
- packages/xchain-terra/src/types/terra.ts
- packages/xchain-terra/src/util.ts
to avoid to import `*/lib` - for `xchain-doget|terra` only
> Quick fix imports

- packages/xchain-util/README.md
- packages/xchain-util/src/bn.ts
Added basic Usage Examples 
Fixed typo in bn.ts.
> Updated readme to reflect packages functions

- packages/xchain-binance/CHANGELOG.md
- packages/xchain-bitcoin/CHANGELOG.md
- packages/xchain-bitcoincash/CHANGELOG.md
- packages/xchain-client/CHANGELOG.md
- packages/xchain-doge/CHANGELOG.md
- packages/xchain-ethereum/CHANGELOG.md
- packages/xchain-litecoin/CHANGELOG.md
- packages/xchain-terra/CHANGELOG.md
- packages/xchain-terra/package.json
- packages/xchain-util/CHANGELOG.md
Updated CHANGELOG for touched packages from branch deposit() and incremented Terra package version.
> Updated changelog 

- packages/xchain-bitcoincash/src/client.ts
- packages/xchain-bitcoincash/src/index.ts
- packages/xchain-ethereum/src/client.ts
- packages/xchain-ethereum/src/index.ts
- packages/xchain-litecoin/src/client.ts
- packages/xchain-litecoin/src/index.ts
to export * from consts
FIX #571
> FIX: 571 build is broken. check imports 

- packages/xchain-ethereum/CHANGELOG.md
- packages/xchain-ethereum/__tests__/client.testnet.test.ts
- packages/xchain-ethereum/__tests__/util.test.ts
- packages/xchain-ethereum/src/client.ts
- packages/xchain-ethereum/src/types/client-types.ts
- packages/xchain-ethereum/src/utils.ts
> Changes to support Ledger ETH - part 1

- packages/xchain-ethereum/CHANGELOG.md
- packages/xchain-ethereum/__tests__/client.testnet.test.ts
- packages/xchain-ethereum/__tests__/util.test.ts
- packages/xchain-ethereum/src/client.ts
- packages/xchain-ethereum/src/types/client-types.ts
- packages/xchain-ethereum/src/utils.ts
> Changes to support Ledger ETH - part 2

- packages/xchain-thornode/CHANGELOG.md
- packages/xchain-thornode/README.md
- packages/xchain-thornode/package.json
- packages/xchain-thornode/src/generated/thornodeApi/api.ts
- yarn.lock
> [xchain-thornode] Update to latest THORNode 1.95.0

- packages/xchain-thorchain/CHANGELOG.md
- packages/xchain-thorchain/__tests__/client.test.ts
- packages/xchain-thorchain/__tests__/util.test.ts
- packages/xchain-thorchain/package.json
- packages/xchain-thorchain/src/client.ts
- packages/xchain-thorchain/src/types/client-types.ts
- packages/xchain-thorchain/src/util.ts
- yarn.lock
https://discord.com/channels/838986635756044328/842252939149967382/threads/1027702970105745449
> remove `getDefaultClientUrl()` and `getChainIds`

- packages/xchain-thorchain-amm/CHANGELOG.md
- packages/xchain-thorchain-amm/package.json
- packages/xchain-thorchain-amm/src/wallet.ts
- packages/xchain-thorchain/CHANGELOG.md
- packages/xchain-thorchain/__tests__/client.test.ts
- packages/xchain-thorchain/package.json
- packages/xchain-thorchain/src/client.ts
changed Stagenet chain id's in Thorchain-amm and chain-thorchain
> updated chain id's

- README.md
- packages/xchain-thorchain-amm/README.md
- packages/xchain-thorchain-query/README.md
> updated query/ amm and master read me

- packages/xchain-thorchain/CHANGELOG.md
- packages/xchain-thorchain/__e2e__/thorchain-client.e2e.ts
- packages/xchain-thorchain/package.json
- packages/xchain-thorchain/src/client.ts
- packages/xchain-thorchain/src/types/client-types.ts
- packages/xchain-thorchain/src/util.ts
to `transfer` and  `deposit`. Bump v.0.27.5
> [xchain-tc] Add optional `sequence`

- examples/check-tx/README.md
- examples/check-tx/check-tx.ts
- examples/do-swap/doSend.ts
- examples/do-swap/doSwap.ts
- examples/do-swap/package.json
Small update to examples folder.
> add bsc, fixed checktx

- .github/workflows/on-push.yaml
- package.json
https://github.com/xchainjs/xchainjs-lib/issues/853
> Add examples on CI

- package.json
- packages/xchain-litecoin/src/types/ledger.ts
- yarn.lock
https://github.com/xchainjs/xchainjs-lib/issues/864
> Force newer version of Jest dependency because of vulnerability

- examples/check-tx/yarn.lock
- examples/do-swap/yarn.lock
- examples/estimate-swap/yarn.lock
- examples/liquidity/yarn.lock
- examples/loans/yarn.lock
- package.json
- packages/xchain-crypto/package.json
- yarn.lock
https://github.com/xchainjs/xchainjs-lib/issues/874
Also review and integrate this PR: 
https://github.com/xchainjs/foundry-primitives-js/pull/4
> Fix critical vulnerability on crypto-js dependency

- examples/liquidity/estimate-withdraw-saver.ts
- packages/xchain-thorchain-amm/CHANGELOG.md
- packages/xchain-thorchain-amm/package.json
- packages/xchain-thorchain-query/CHANGELOG.md
- packages/xchain-thorchain-query/package.json
- packages/xchain-thorchain-query/src/thorchain-query.ts
> 888 Fix estimate withdraw

- packages/xchain-midgard-query/CHANGELOG.md
- packages/xchain-midgard-query/__e2e__/thorchain-midgard-query-e2e.ts
- packages/xchain-midgard-query/package.json
- packages/xchain-midgard-query/src/midgard-query.ts
- packages/xchain-thorchain-amm/CHANGELOG.md
- packages/xchain-thorchain-amm/package.json
- packages/xchain-thorchain-query/CHANGELOG.md
- packages/xchain-thorchain-query/package.json
> 894 midgard query decimals

- packages/xchain-cosmos/CHANGELOG.md
- packages/xchain-cosmos/__e2e__/cosmos-client.e2e.ts
- packages/xchain-cosmos/package.json
- packages/xchain-cosmos/src/client.ts
- packages/xchain-mayachain/CHANGELOG.md
- packages/xchain-mayachain/package.json
- packages/xchain-mayachain/src/client.ts
- packages/xchain-thorchain/CHANGELOG.md
- packages/xchain-thorchain/__e2e__/thorchain-client.e2e.ts
- packages/xchain-thorchain/package.json
- packages/xchain-thorchain/src/client.ts
https://github.com/xchainjs/xchainjs-lib/issues/902
> Fix prepareTx for uninitialize addresses

- packages/xchain-thorchain-amm/CHANGELOG.md
- packages/xchain-thorchain-amm/package.json
- packages/xchain-thorchain/CHANGELOG.md
- packages/xchain-thorchain/package.json
- packages/xchain-thorchain/src/client.ts
> 912 url thorchain fallback

- packages/xchain-mayachain-amm/CHANGELOG.md
- packages/xchain-mayachain-amm/package.json
- packages/xchain-mayachain-query/CHANGELOG.md
- packages/xchain-mayachain-query/package.json
- packages/xchain-mayamidgard-query/CHANGELOG.md
- packages/xchain-mayamidgard-query/package.json
> Maya dependencies

- .gitignore
- LICENSE.txt
- README.md
To  visually see the new README, go to https://github.com/xchainjs/xchainjs-lib/tree/1090-update-readme
> 1090 README

- .changeset/unlucky-lies-shake.md
- packages/xchain-wallet/src/wallet.ts
Add CosmosTxParams to estimateTransferFees
https://github.com/xchainjs/xchainjs-lib/issues/1236
> 1236 add cosmos type to estimate transfer

- .changeset/tricky-dolls-wink.md
- packages/xchain-client/src/types.ts
https://github.com/xchainjs/xchainjs-lib/issues/1240
> Add info types for assets

- .changeset/eighty-beers-move.md
- packages/xchain-evm/src/clients/client.ts
- packages/xchain-evm/src/signers/keystoreSigner.ts
- packages/xchain-evm/src/signers/ledgerSigner.ts
- packages/xchain-evm/src/types/signer-types.ts
Fix bug with send and approve for LedgerSigner on EVM client
> Fix bug EVM ledger signer

- .changeset/funny-olives-approve.md
- packages/xchain-mayachain-query/src/mayachain-query.ts
- packages/xchain-mayachain/__e2e__/mayachain-client.e2e.ts
- packages/xchain-util/__tests__/asset.test.ts
- packages/xchain-util/src/asset.ts
https://github.com/xchainjs/xchainjs-lib/issues/1270
> refactor asset from string

- .changeset/fast-months-sip.md
- packages/xchain-aggregator/src/types.ts
https://github.com/xchainjs/xchainjs-lib/issues/1294
> Add parameters to aggregator

- .changeset/cold-dryers-tap.md
- .changeset/mean-seals-provide.md
- packages/xchain-bsc/src/const.ts
- packages/xchain-ethereum/src/const.ts
- packages/xchain-thorchain/src/clientKeystore.ts
https://github.com/xchainjs/xchainjs-lib/issues/1389
> Lower BSC fees and add clear error message

- .changeset/empty-parts-take.md
- packages/xchain-evm-providers/src/providers/etherscan-v2/utils.ts
- packages/xchain-evm-providers/src/providers/etherscan/utils.ts
- packages/xchain-evm/__e2e__/AvaxClient.e2e.ts
- packages/xchain-evm/src/utils.ts
Fixing bugs discover testing new version on Asgardex
https://github.com/asgardex/asgardex-desktop/pull/790
> Fix approve MAX_AMOUNT

- .changeset/true-mice-sing.md
- packages/xchain-evm/src/clients/client.ts
FIx for https://github.com/asgardex/asgardex-desktop/pull/790
> Fix approve max amount

- packages/xchain-aggregator/__mocks__/mayachain/mayanode/api.ts
- packages/xchain-aggregator/__mocks__/mayachain/midgard/api.ts
- packages/xchain-aggregator/__mocks__/thorchain/midgard/api.ts
- packages/xchain-aggregator/__mocks__/thorchain/thornode/api.ts
- packages/xchain-bitcoin/__mocks__/bitgo.ts
- packages/xchain-bitcoin/__mocks__/haskoin.ts
- packages/xchain-bitcoin/__mocks__/sochain.ts
- packages/xchain-bitcoincash/__mocks__/bitgo.ts
- packages/xchain-bitcoincash/__mocks__/haskoin.ts
- packages/xchain-bitcoincash/__mocks__/thornode.ts
- packages/xchain-dash/__mocks__/dash-mocks.ts
- packages/xchain-doge/__mocks__/blockcypher.ts
- packages/xchain-doge/__mocks__/sochain.ts
- packages/xchain-doge/__mocks__/thornode.ts
- packages/xchain-litecoin/__mocks__/sochain.ts
- packages/xchain-litecoin/__mocks__/thornode-api.ts
- packages/xchain-mayachain-amm/__mocks__/mayanode-api/mayanode-api.ts
- packages/xchain-mayachain-amm/__mocks__/midgard-api/midgard-api.ts
- packages/xchain-mayachain-query/__mocks__/mayanode-api.ts
- packages/xchain-mayachain-query/__mocks__/midgard-api.ts
- packages/xchain-mayamidgard-query/__mocks__/midgard/midgardApi.ts
- packages/xchain-midgard-query/__mocks__/midgard-api.ts
- packages/xchain-thorchain-amm/__mocks__/midgard-api.ts
- packages/xchain-thorchain-amm/__mocks__/thornode-api.ts
- packages/xchain-thorchain-query/__mocks__/midgard-api.ts
- packages/xchain-thorchain-query/__mocks__/thornode-api.ts
- packages/xchain-utxo-providers/__mocks__/haskoin.ts
- packages/xchain-utxo-providers/__mocks__/sochain.ts
- packages/xchain-zcash/__mocks__/nownodes.ts
`MockAdapter.onGet().reply()` takes an asynchronous function.
> pass async closures to axios-mock-adapter

- .changeset/eleven-times-tan.md
- .changeset/shy-wombats-wink.md
Create mising changeset and fix old one including non real packages
> Add missing changeset and correct old one
