- packages/xchain-binance/__tests__/client.test.ts
- packages/xchain-binance/src/client.ts
- packages/xchain-bitcoin/__tests__/client.test.ts
- packages/xchain-bitcoin/src/client.ts
- packages/xchain-bitcoin/src/types/client-types.ts
- packages/xchain-bitcoin/src/utils.ts
- packages/xchain-client/src/types.ts
- packages/xchain-cosmos/src/client.ts
- packages/xchain-thorchain/src/client.ts
> Update fee handling

- packages/xchain-binance/__tests__/client.test.ts
- packages/xchain-binance/__tests__/util.test.ts
- packages/xchain-binance/src/client.ts
- packages/xchain-binance/src/types/binance.ts
- packages/xchain-binance/src/util.ts
- packages/xchain-client/src/types.ts
- packages/xchain-cosmos/__tests__/client.test.ts
- packages/xchain-cosmos/__tests__/sdk-client.test.ts
- packages/xchain-cosmos/src/client.ts
- packages/xchain-cosmos/src/cosmos/sdk-client.ts
- packages/xchain-thorchain/__tests__/client.test.ts
- packages/xchain-thorchain/src/client.ts
- add getTransactionData in XChainClient
- add getTransactionData in XChainBinance
- add getTransactionData in XChainCosmos
- add getTransactionData in XChainThorchain
Part of #60 
Fix #66
> getTransactionData(XChainClient, BinanceChain, Cosmos, ThorChain)

- packages/xchain-binance/__tests__/client.test.ts
- packages/xchain-binance/src/client.ts
- packages/xchain-bitcoin/src/client.ts
> Fix build + tests

- packages/xchain-binance/src/client.ts
- packages/xchain-client/src/types.ts
> [xcain-binance] getTransactions add asset parameter #78

- packages/xchain-cosmos/src/client.ts
- packages/xchain-thorchain/src/client.ts
there was assets objects plain comparision via references which leaded to empty balances. fixed to compare assets' strings
> fixed wrong assets comparission

- packages/xchain-polkadot/__tests__/client.test.ts
- packages/xchain-polkadot/src/client.ts
New Features; 
- Adding support for transafer without memo 
- Using `utility.batchAll` instead of `utility.batch`. This makes the transaction atomic. 
This is WIP due to tests not able to support `utility.batchAll`.
> [wip] Polkadot Batch Support

- packages/xchain-binance/CHANGELOG.md
- packages/xchain-binance/package.json
- packages/xchain-bitcoin/CHANGELOG.md
- packages/xchain-bitcoin/package.json
- packages/xchain-bitcoincash/CHANGELOG.md
- packages/xchain-bitcoincash/__tests__/client.test.ts
- packages/xchain-bitcoincash/package.json
- packages/xchain-bitcoincash/src/client.ts
- packages/xchain-client/CHANGELOG.md
- packages/xchain-client/package.json
- packages/xchain-cosmos/CHANGELOG.md
- packages/xchain-cosmos/package.json
- packages/xchain-crypto/CHANGELOG.md
- packages/xchain-crypto/package.json
- packages/xchain-ethereum/CHANGELOG.md
- packages/xchain-ethereum/package.json
- packages/xchain-litecoin/CHANGELOG.md
- packages/xchain-litecoin/package.json
- packages/xchain-polkadot/CHANGELOG.md
- packages/xchain-polkadot/package.json
- packages/xchain-thorchain/CHANGELOG.md
- packages/xchain-thorchain/package.json
- packages/xchain-util/CHANGELOG.md
- packages/xchain-util/package.json
- packages/xchain-util/src/chain.const.ts
- adds `yarn clean` to `yarn prepublishOnly`
- fixes small linting bug in utils where Litecoin was declared twice in chain consts.
> clean lib folder before build when publishing to npm

- packages/xchain-ethereum/CHANGELOG.md
- packages/xchain-ethereum/package.json
- packages/xchain-ethereum/src/client.ts
- packages/xchain-ethereum/src/types/client-types.ts
from ethers.js docs...
"The apiKey can be a string Project ID or an object with the properties projectId and projectSecret to specify a Project Secret which can be used on non-public sources (like on a server) to further secure your API access and quotas."
makes project secret optional.
> allows infura creds secret to be optional

- packages/xchain-bitcoin/CHANGELOG.md
- packages/xchain-bitcoin/package.json
- packages/xchain-bitcoin/src/index.ts
- packages/xchain-bitcoincash/CHANGELOG.md
- packages/xchain-bitcoincash/package.json
- packages/xchain-bitcoincash/src/client.ts
- packages/xchain-litecoin/CHANGELOG.md
- packages/xchain-litecoin/package.json
- packages/xchain-litecoin/src/client.ts
- packages/xchain-litecoin/src/index.ts
chore: fix mainnet urls for litecoin and bch
> fix: litecoin export `Utils.validateAddress` and bitcoincash `Utils.validateAddress`

- packages/xchain-bitcoincash/CHANGELOG.md
- packages/xchain-bitcoincash/__tests__/client.test.ts
- packages/xchain-bitcoincash/package.json
- packages/xchain-bitcoincash/src/utils.ts
- `utils:parseTransaction` added stripping prefixes to the address mapper
- bump version to `v0.10.1`
> Fix bitcoincash transaction prefixed address

- packages/xchain-bitcoin/src/client.ts
- packages/xchain-bitcoincash/src/client.ts
- packages/xchain-ethereum/src/client.ts
- packages/xchain-litecoin/src/client.ts
The ClientParams types which are used in the constructor of the client are now also exported. Then I can use the type also when I'm initializing the clients.
> export client params types which are used in constructor

- packages/xchain-bitcoin/CHANGELOG.md
- packages/xchain-bitcoin/package.json
- packages/xchain-bitcoin/src/utils.ts
- packages/xchain-bitcoincash/CHANGELOG.md
- packages/xchain-bitcoincash/package.json
- packages/xchain-bitcoincash/src/utils.ts
- packages/xchain-litecoin/CHANGELOG.md
- packages/xchain-litecoin/package.json
- packages/xchain-litecoin/src/utils.ts
this is a followup to fix #336, where we leave the memo in the ouputs to make sure accumulate includes enough inputs to cover the tx costs if a memo is included. we then re-add the memo using psbt.addOutput() to avoid the tx to be flagged with dust error.
> refactored utils.buildTx() in BCH,LTC,BTC

- packages/xchain-ethereum/CHANGELOG.md
- packages/xchain-ethereum/package.json
- packages/xchain-ethereum/src/client.ts
- fixed `getTransactions` method
- bumped `v0.21.2`
works well with local `yarn link` for ASGDX project (related to https://github.com/thorchain/asgardex-electron/issues/1487)
https://user-images.githubusercontent.com/67793194/120477149-1d6acc00-c3b4-11eb-9afe-9cd1a571113a.mov
closes #343
> ETH: fix getTransactions filtering boundaries

- packages/xchain-litecoin/CHANGELOG.md
- packages/xchain-litecoin/package.json
- packages/xchain-litecoin/src/utils.ts
- fix adding duplicated memo output in the `Utils.buildTx()`
> Fix duplicated memo output

- packages/xchain-thorchain/CHANGELOG.md
- packages/xchain-thorchain/package.json
- packages/xchain-thorchain/src/client.ts
to avoid failing withdraw transactions + bump `v0.16.1`
Related issue https://github.com/thorchain/asgardex-electron/issues/1541
> [xchain-thorchain] Double `fee.gas` to `20m`

- packages/xchain-client/src/BaseXChainClient.ts
- packages/xchain-ethereum/CHANGELOG.md
- packages/xchain-ethereum/__tests__/client.testnet.test.ts
- packages/xchain-ethereum/package.json
- packages/xchain-ethereum/src/client.ts
- packages/xchain-ethereum/src/types/client-types.ts
Before `isApproved` returned always `false`, it missed to passed`owner` address to ERC20 contract `allowance` function. This PR fixes it. It will also fixes issues based on failing `allowance` handling in ASGARDEX desktop (see https://github.com/thorchain/asgardex-electron/issues/1595, https://github.com/thorchain/asgardex-electron/issues/1594)
> [xchain-eth] Fix `isApproved` call

- packages/xchain-bitcoin/CHANGELOG.md
- packages/xchain-bitcoin/package.json
- packages/xchain-bitcoin/src/client.ts
- packages/xchain-litecoin/CHANGELOG.md
- packages/xchain-litecoin/package.json
- packages/xchain-litecoin/src/client.ts
- refactored LTC client methods to use regular method syntax (not fat arrow) in order for call to super.xxx() to work properly
- refactored BTC client methods to use regular method syntax (not fat arrow) in order for call to super.xxx() to work properly
> refactored client methods to use regular method syntax (not fat arrow)

- packages/xchain-binance/CHANGELOG.md
- packages/xchain-binance/package.json
- packages/xchain-binance/src/client.ts
- packages/xchain-bitcoin/src/client.ts
- packages/xchain-cosmos/CHANGELOG.md
- packages/xchain-cosmos/package.json
- packages/xchain-cosmos/src/client.ts
- packages/xchain-cosmos/src/cosmos/sdk-client.ts
- packages/xchain-ethereum/CHANGELOG.md
- packages/xchain-ethereum/package.json
- packages/xchain-ethereum/src/client.ts
- packages/xchain-polkadot/CHANGELOG.md
- packages/xchain-polkadot/package.json
- packages/xchain-polkadot/src/client.ts
- packages/xchain-thorchain/CHANGELOG.md
- packages/xchain-thorchain/package.json
- packages/xchain-thorchain/src/client.ts
Finishes removing fat-arrow methods throughout the codebase; this was started by #380. Using fat-arrow methods assigned as fields implicitly binds their value of `this` to the value present in the constructor; this can cause unexpected interactions with the JS prototype inheritance model.
(This is a part of the changeset currently known as #376; I'm working on factoring out some of its parts that are separable concerns and make the diffs hard to read if all rolled into one thing.)
> Refactor remaining client objects to avoid fat-arrow methods

- packages/xchain-binance/src/client.ts
- packages/xchain-bitcoin/src/blockstream-api.ts
- packages/xchain-bitcoin/src/client.ts
- packages/xchain-bitcoin/src/haskoin-api.ts
- packages/xchain-bitcoin/src/ledger.ts
- packages/xchain-bitcoin/src/sochain-api.ts
- packages/xchain-bitcoin/src/utils.ts
- packages/xchain-bitcoincash/src/client.ts
- packages/xchain-bitcoincash/src/haskoin-api.ts
- packages/xchain-bitcoincash/src/node-api.ts
- packages/xchain-bitcoincash/src/utils.ts
- packages/xchain-cosmos/src/client.ts
- packages/xchain-cosmos/src/cosmos/sdk-client.ts
- packages/xchain-crypto/src/crypto.ts
- packages/xchain-ethereum/src/client.ts
- packages/xchain-ethereum/src/etherscan-api.ts
- packages/xchain-ethereum/src/ethplorer-api.ts
- packages/xchain-ethereum/src/utils.ts
- packages/xchain-litecoin/__tests__/client.test.ts
- packages/xchain-litecoin/src/client.ts
- packages/xchain-litecoin/src/ledger.ts
- packages/xchain-litecoin/src/node-api.ts
- packages/xchain-litecoin/src/sochain-api.ts
- packages/xchain-litecoin/src/utils.ts
- packages/xchain-polkadot/src/client.ts
- packages/xchain-thorchain/src/client.ts
This is based on #381.
There are a lot of unhelpful try/catch statements in the library (generally of the form `try { } catch (e) { return Promise.reject(e) }`) which don't actually do anything. This gets rid of them.
(This is a part of the changeset currently known as #376; I'm working on factoring out some of its parts that are separable concerns and make the diffs hard to read if all rolled into one thing.)
> Remove unhelpful try/catch statements

- packages/xchain-bitcoincash/src/utils.ts
[`transfer`](https://github.com/xchainjs/xchainjs-lib/blob/master/packages/xchain-bitcoincash/src/client.ts#L289) method of xchain-bitcoincache client is not able sign list of utxos because some of them were filtered by [`buildTx`](https://github.com/xchainjs/xchainjs-lib/blob/master/packages/xchain-bitcoincash/src/utils.ts#L269), as the result [`No input at index: X`](https://github.com/bitcoinjs/bitcoinjs-lib/blob/239711bf4ef00651af92049bcdf88b12252b945c/ts_src/transaction_builder.ts#L1252) exception is thrown.
Return only list of used inputs.
> [xchain-bitcoincash] FIX: buildTx returns only used utxos

- packages/xchain-thorchain/CHANGELOG.md
- packages/xchain-thorchain/package.json
- packages/xchain-thorchain/src/util.ts
`30m` seems to be another recommended value for gas
^ Cosmos dev Discord ^ https://discord.com/channels/669268347736686612/699634178173698108/889188531015143504
Incl. bump / prepare v0.19.1
> [xchain-thorchain] Increase `gas` limit to `30m`

- packages/xchain-thorchain/src/client.ts
This patch fixes the asset notation for synthetic assets. While native assets are denoted `<Network>.<Symbol>`, synth assets are denoted `<Network>/<Symbol>`.
Synths are expected to be described as CryptoAsset like: `{network: 'THOR', ticker: 'eth/usdt', symbol: 'eth/usdt-0xbeef' }`.
This patch only concerns about the notation, not about other aspects of the client (like sufficient balance check).
> Fix synth notation

- packages/xchain-terra/CHANGELOG.md
- packages/xchain-terra/__tests__/util.test.ts
- packages/xchain-terra/package.json
- packages/xchain-terra/src/client.ts
- packages/xchain-terra/src/const.ts
- packages/xchain-terra/src/index.ts
- packages/xchain-terra/src/util.ts
- packages/xchain-util/CHANGELOG.md
- packages/xchain-util/package.json
- packages/xchain-util/src/chain.ts
Fix #483
Close #481
Close #482
> Few fixes for xchain-terra

- packages/xchain-thorchain/CHANGELOG.md
- packages/xchain-thorchain/__tests__/client.test.ts
- packages/xchain-thorchain/__tests__/util.test.ts
- packages/xchain-thorchain/package.json
- packages/xchain-thorchain/src/client.ts
- packages/xchain-thorchain/src/types/client-types.ts
- packages/xchain-thorchain/src/util.ts
> Resolve: [xchain-tc] Make chainId configurable

- packages/xchain-thorchain/CHANGELOG.md
- packages/xchain-thorchain/package.json
- packages/xchain-thorchain/src/util.ts
We recently started seeing send and message txs fail because the gasUsed is slightly above the 2000000 limit starting from about yesterday. This increases the limit constant for TC transactions.
> [xchain-thorchain] Increase gas limit to 3000000

- packages/xchain-thorchain/package.json
- packages/xchain-thorchain/src/client.ts
- packages/xchain-thorchain/src/util.ts
Register types for encoding thorchain's custom messages on client init so they will always be available, even if you don't use the built in `deposit` and `transfer` functions
> xchain-thorchain: Register codecs on client init

- .eslintrc
- packages/xchain-terra/CHANGELOG.md
- packages/xchain-terra/src/client.ts
- packages/xchain-terra/src/index.ts
- packages/xchain-terra/src/types/client.ts
- packages/xchain-terra/src/types/index.ts
- packages/xchain-terra/src/types/terra.ts
- packages/xchain-terra/src/util.ts
> Few updates for xchain-terra

- packages/xchain-util/CHANGELOG.md
- packages/xchain-util/package.json
- packages/xchain-util/src/asset.test.ts
- packages/xchain-util/src/asset.ts
> [xchain-util] Support `UST` in `currencySymbolByAsset`

- packages/xchain-binance/package.json
- packages/xchain-terra/package.json
this to avoid peerDeps errors when running `npm install`
> xchain utils version update

- packages/xchain-binance/__tests__/client.test.ts
- packages/xchain-bitcoin/__tests__/client.test.ts
- packages/xchain-bitcoincash/__tests__/client.test.ts
- packages/xchain-cosmos/__tests__/client.test.ts
- packages/xchain-doge/__tests__/client.test.ts
- packages/xchain-ethereum/CHANGELOG.md
- packages/xchain-ethereum/__tests__/client.testnet.test.ts
- packages/xchain-ethereum/package.json
- packages/xchain-ethereum/src/client.ts
- packages/xchain-litecoin/__tests__/client.test.ts
- packages/xchain-polkadot/__tests__/client.test.ts
- packages/xchain-terra/__tests__/client.test.ts
- packages/xchain-thorchain/__tests__/client.test.ts
Phrases in the ethereum client should not be required to create a client. 
The eth client is the only client where phrase is not optional. `purgeClient()` should remove the phrase. Methods that require a phrase should throw errors if it is not present. 
I've added tests to the other clients to ensure they work the same way. 
I believe this supersedes of #374 
Close #374
> Unrequire phrase

- packages/xchain-thorchain/CHANGELOG.md
- packages/xchain-thorchain/package.json
- packages/xchain-thorchain/src/util.ts
Discussion at Discord https://discord.com/channels/838986635756044328/967336653075132448
Note: It should be a temporary workaround only. As suggested in https://discord.com/channels/838986635756044328/967336653075132448/967365186774257664 another (better) fix using `gas: auto` / `gasAdjustment: 1.5` is needed in long term -> :eyes:   [ [xchain-thorchain] Another try to use gas: auto + gasAdjustment: 1.5 (or higher) #556 ](https://github.com/xchainjs/xchainjs-lib/issues/556)
> [xchain-thorchain] Increase DEFAULT_GAS_VALUE to 4000000

- packages/xchain-terra/CHANGELOG.md
- packages/xchain-terra/__tests__/util.test.ts
- packages/xchain-terra/package.json
- packages/xchain-terra/src/client.ts
- packages/xchain-terra/src/util.ts
to ignore non-native Terra or invalid assets. Bump `xchain-terra@0.1.1`.
Fixes #559
> [xchain-terra] Fix `coinsToBalances`

- packages/xchain-client/CHANGELOG.md
- packages/xchain-client/package.json
to include fee bounds (b76d430) - still missing in 0.11.2
> Bump xchain-client@v.0.11.3

- packages/xchain-ethereum/__tests__/client.mainnet.test.ts
- packages/xchain-ethereum/__tests__/client.testnet.test.ts
- packages/xchain-ethereum/package.json
- packages/xchain-ethereum/src/client.ts
No need to multiply fee rates. It's already done in `standardFeeRates` of `xchain-client` ([code](https://github.com/xchainjs/xchainjs-lib/blob/723608214ce512deab80cdb64d64e74b859fefee/packages/xchain-client/src/feeRates.ts#L7-L13)). This bug was  introduced in #582 as part of `xchain-ethereum@0.25.alpha.1` _(my bad)_.
Bump `xchain-ethereum@0.25.alpha.3`
> [xchain-ethereum] Fix `estimateGasPrices`

- packages/xchain-thorchain/CHANGELOG.md
- packages/xchain-thorchain/__tests__/client.test.ts
- packages/xchain-thorchain/src/client.ts
- packages/xchain-thorchain/src/types/client-types.ts
- packages/xchain-thorchain/src/util.ts
`DEFAULT_GAS_LIMIT_VALUE` or `DEPOSIT_GAS_LIMIT_VALUE` (both can be
overridden by users in `transfer` or `deposit`).
> [xchain-thorchain] Disable estimation of gas

- packages/xchain-cosmos/CHANGELOG.md
- packages/xchain-cosmos/__tests__/client.test.ts
- packages/xchain-cosmos/__tests__/util.test.ts
- packages/xchain-cosmos/package.json
- packages/xchain-cosmos/src/client.ts
- packages/xchain-cosmos/src/const.ts
- packages/xchain-cosmos/src/cosmos/sdk-client.ts
- packages/xchain-cosmos/src/cosmos/types.ts
- packages/xchain-cosmos/src/index.ts
- packages/xchain-cosmos/src/types/client-types.ts
- packages/xchain-cosmos/src/util.ts
Note: PR continues changes started in #597 (thx to @towanTG)
> [xchain-cosmos] Misc. updates to support ATOM - part 1

- packages/xchain-cosmos/CHANGELOG.md
- packages/xchain-cosmos/__tests__/client.test.ts
- packages/xchain-cosmos/__tests__/sdk-client.test.ts
- packages/xchain-cosmos/__tests__/util.test.ts
- packages/xchain-cosmos/package.json
- packages/xchain-cosmos/src/client.ts
- packages/xchain-cosmos/src/cosmos/sdk-client.ts
- packages/xchain-cosmos/src/cosmos/types.ts
- packages/xchain-cosmos/src/util.ts
- packages/xchain-thorchain/CHANGELOG.md
- packages/xchain-thorchain/package.json
- packages/xchain-thorchain/src/client.ts
- packages/xchain-thorchain/src/types/client-types.ts
- packages/xchain-thorchain/src/util.ts
- yarn.lock
> [xchain-cosmos|thorchain] Misc. updates - mostly to support ATOM - part 2

- packages/xchain-cosmos/CHANGELOG.md
- packages/xchain-cosmos/__tests__/client.test.ts
- packages/xchain-cosmos/__tests__/util.test.ts
- packages/xchain-cosmos/package.json
- packages/xchain-cosmos/src/client.ts
- packages/xchain-cosmos/src/const.ts
- packages/xchain-cosmos/src/util.ts
- packages/xchain-thorchain/CHANGELOG.md
- packages/xchain-thorchain/package.json
> [xchain-cosmos|thorchain] Finalize ATOM support - bump pgks

- packages/xchain-cosmos/CHANGELOG.md
- packages/xchain-cosmos/__tests__/sdk-client.test.ts
- packages/xchain-cosmos/package.json
- packages/xchain-cosmos/src/client.ts
- packages/xchain-cosmos/src/cosmos/sdk-client.ts
- packages/xchain-cosmos/src/cosmos/types.ts
- packages/xchain-cosmos/src/util.ts
- packages/xchain-thorchain/CHANGELOG.md
- packages/xchain-thorchain/package.json
- packages/xchain-thorchain/src/client.ts
> [xchain-cosmos] Changes needed to support Ledger

- packages/xchain-bitcoincash/CHANGELOG.md
- packages/xchain-bitcoincash/package.json
- packages/xchain-bitcoincash/src/haskoin-api.ts
- yarn.lock
Similar to #492 + #493, but for BCH.
Bump `xchain-bch@0.13.2` + update it dependencies for using latest `xchain-client@0.11.3"
> [xchain-bch] Handle Haskoins 500 error

- packages/xchain-doge/CHANGELOG.md
- packages/xchain-doge/package.json
- packages/xchain-doge/src/utils.ts
`setMaximumFeeRate` needs to be increased to cover current fees of [750000sats/byte](https://thornode.ninerealms.com/thorchain/inbound_addresses?height=7526662). Bug was reported in Discord `#asgardex-desktop` https://discord.com/channels/838986635756044328/839002220942721024/1024199604192952340
Before: `650000 sats/byte`
Now: `7500000 sats/byte` (10x of current fee rate)
Comparing to
- xchain-thorswap: `650000000` ([code](https://github.com/thorswap/thorswap-xchainjs/blob/main/packages/xchain-doge/src/utils.ts#L214))
- THORWallet-xchainjs `5500000` ([code](https://github.com/THORWallet/THORWallet-xchainjs/blob/master/packages/xchain-doge/src/utils.ts#L172))
> [xchain-doge] Fix maximum fee rate

- packages/xchain-avax/CHANGELOG.md
- packages/xchain-avax/package.json
- packages/xchain-avax/src/const.ts
- packages/xchain-binance/CHANGELOG.md
- packages/xchain-binance/package.json
- packages/xchain-binance/src/const.ts
- packages/xchain-bitcoin/CHANGELOG.md
- packages/xchain-bitcoin/package.json
- packages/xchain-bitcoin/src/const.ts
- packages/xchain-bitcoincash/CHANGELOG.md
- packages/xchain-bitcoincash/package.json
- packages/xchain-bitcoincash/src/const.ts
- packages/xchain-cosmos/CHANGELOG.md
- packages/xchain-cosmos/package.json
- packages/xchain-cosmos/src/const.ts
- packages/xchain-doge/CHANGELOG.md
- packages/xchain-doge/package.json
- packages/xchain-doge/src/const.ts
- packages/xchain-ethereum/CHANGELOG.md
- packages/xchain-ethereum/package.json
- packages/xchain-ethereum/src/const.ts
- packages/xchain-litecoin/CHANGELOG.md
- packages/xchain-litecoin/package.json
- packages/xchain-litecoin/src/const.ts
- packages/xchain-mayachain/CHANGELOG.md
- packages/xchain-mayachain/package.json
- packages/xchain-mayachain/src/const.ts
- packages/xchain-thorchain/CHANGELOG.md
- packages/xchain-thorchain/package.json
- packages/xchain-thorchain/src/const.ts
In https://github.com/xchainjs/xchainjs-lib/pull/705 we lost type safety of Chain, but with this small change anyone can bring it back if needed.
`as const` is a more type safety definition than `string`. Example (compare different type of `Chains` vs. `Chains2`) :
```ts
type Chain = string
const AVAXChain: Chain = 'AVAX'
const BTCChain: Chain = 'BTC'
const LTCChain: Chain = 'LTC'
const CHAINS = [AVAXChain, BTCChain, LTCChain] as const
type Chains = typeof CHAINS[number] // type Chains = string
// vs.
const AVAXChain2 = 'AVAX' as const
const BTCChain2 = 'BTC' as const
const LTCChain2 = 'LTC' as const
const CHAINS2 = [AVAXChain2, BTCChain2, LTCChain2] as const
type Chains2 = typeof CHAINS2[number] // type Chains2 = "AVAX" | "BTC" | "LTC"
```
Bump packages.
> A more type safety export of `{XYZ}Chain`

- packages/xchain-client/README.md
- packages/xchain-cosmos-sdk/src/client.ts
- packages/xchain-evm-providers/README.md
- packages/xchain-midgard-query/src/midgard-cache.ts
- packages/xchain-midgard-query/src/midgard-query.ts
- packages/xchain-midgard-query/src/types.ts
- packages/xchain-midgard-query/src/utils/midgard.ts
- packages/xchain-util/src/cached-value.ts
- packages/xchain-utxo-providers/README.md
https://github.com/xchainjs/xchainjs-lib/issues/843
Necessary to unblock this one: 
https://github.com/xchainjs/xchainjs.github.io/pull/37
> 843 update docs

- .changeset/lovely-roses-float.md
- .changeset/rude-pumpkins-notice.md
- packages/xchain-mayachain-query/src/utils/mayanode.ts
- packages/xchain-mayamidgard-query/src/midgard-api.ts
Mayachain Midgard and Mayachain Node backup endpoints added. To be able to add the Mayachain client URL, Cosmos-sdk package needs to be able to work with several clients.
> 1118 Mayachain backup endpoints

- .changeset/mean-cows-deny.md
- .changeset/polite-flowers-grow.md
- examples/aggregator/swap-history.ts
- packages/xchain-aggregator/__e2e__/aggregator.e2e.test.ts
- packages/xchain-aggregator/__e2e__/aggregator.e2e.ts
- packages/xchain-aggregator/__mocks__/@chainflip/sdk/swap.ts
- packages/xchain-aggregator/package.json
- packages/xchain-aggregator/src/protocols/chainflip/chainflipProtocol.ts
- packages/xchain-aggregator/src/protocols/chainflip/utils.ts
- packages/xchain-arbitrum/src/const.ts
- yarn.lock
> add arbitrum to chainflip

- .changeset/violet-students-shop.md
- packages/xchain-arbitrum/__e2e__/arbitrum.e2e.ts
- packages/xchain-arbitrum/src/const.ts
- packages/xchain-avax/__e2e__/avax-client.e2e.ts
- packages/xchain-avax/src/const.ts
- packages/xchain-base/__e2e__/base.e2e.ts
- packages/xchain-base/src/const.ts
- packages/xchain-bsc/__e2e__/bsc-client.e2e.ts
- packages/xchain-bsc/src/const.ts
- packages/xchain-ethereum/__e2e__/eth-client.e2e.ts
- packages/xchain-ethereum/src/const.ts
- packages/xchain-evm-providers/src/providers/etherscan-v2/erc20.json
- packages/xchain-evm-providers/src/providers/etherscan-v2/etherscan-api-types-v2.ts
- packages/xchain-evm-providers/src/providers/etherscan-v2/etherscan-api-v2.ts
- packages/xchain-evm-providers/src/providers/etherscan-v2/etherscan-data-provider-v2.ts
- packages/xchain-evm-providers/src/providers/etherscan-v2/types-v2.ts
- packages/xchain-evm-providers/src/providers/etherscan-v2/utils.ts
- packages/xchain-evm-providers/src/providers/index.ts
This PR updates our Etherscan integration to support the new Etherscan V2 API, as the V1 API is scheduled to be deprecated by the end of the month.
Following the official migration guide ([Etherscan V2 Quickstart](https://docs.etherscan.io/etherscan-v2/v2-quickstart)), the update introduces support for V2 by adding the required chainId parameter.
To ensure maximum compatibility and flexibility, support for V1 has been retained, allowing users to choose between V1 and V2 providers depending on their needs. This is particularly important in case certain chains or explorers (e.g., Snowtrace) diverge from Etherscan's V2 implementation or are not yet fully supported.
By default, V2 is now enabled for Ethereum, Avalanche, Base, BSC, and Arbitrum, which means any integrations using default …
> Etherscan V2

- .changeset/rich-moons-poke.md
- packages/xchain-crypto/package.json
- packages/xchain-crypto/src/crypto.ts
- yarn.lock
https://github.com/xchainjs/foundry-primitives-js
Replacement available in `@noble/hashes` [1.7.1](https://github.com/paulmillr/noble-hashes/releases/tag/1.7.1)
Part of #1449
This also silences a security alert about foundry-primitives-xchainjs depending on a very old version of `crypto-js`.
https://github.com/asgardex/asgardex-desktop/security/dependabot/4
> remove dependency on foundry-primitives fork
